export const abi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "CallerNotContestCreator", type: "error" },
  { inputs: [], name: "DescriptionTooLong", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "TitleEmpty", type: "error" },
  { inputs: [], name: "TitleTooLong", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "newDescription",
        type: "string",
      },
    ],
    name: "ContestDescriptionUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "newTitle",
        type: "string",
      },
    ],
    name: "ContestTitleUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_DESCRIPTION_LENGTH",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_TITLE_LENGTH",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "rowScore", type: "uint256" },
      { internalType: "uint256", name: "colScore", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "uint8", name: "homeQ1LastDigit", type: "uint8" },
          { internalType: "uint8", name: "homeQ2LastDigit", type: "uint8" },
          { internalType: "uint8", name: "homeQ3LastDigit", type: "uint8" },
          { internalType: "uint8", name: "homeFLastDigit", type: "uint8" },
          { internalType: "uint8", name: "awayQ1LastDigit", type: "uint8" },
          { internalType: "uint8", name: "awayQ2LastDigit", type: "uint8" },
          { internalType: "uint8", name: "awayQ3LastDigit", type: "uint8" },
          { internalType: "uint8", name: "awayFLastDigit", type: "uint8" },
          { internalType: "uint8", name: "qComplete", type: "uint8" },
          { internalType: "bool", name: "requestInProgress", type: "bool" },
          { internalType: "bool", name: "gameCompleted", type: "bool" },
        ],
        internalType: "struct IContestTypes.GameScore",
        name: "gameScores",
        type: "tuple",
      },
    ],
    name: "calculateWinningQuarters",
    outputs: [{ internalType: "uint8[]", name: "", type: "uint8[]" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "contestStorage",
    outputs: [{ internalType: "contract Contests", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "fetchAllBoxesByContest",
    outputs: [
      { internalType: "uint256[]", name: "tokenIds", type: "uint256[]" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "fetchAllContestsWithUser",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContestCurrency",
    outputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "string", name: "", type: "string" },
      { internalType: "string", name: "", type: "string" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContestInfo",
    outputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "description", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getGameIdForContest",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "rowScore", type: "uint256" },
      { internalType: "uint256", name: "colScore", type: "uint256" },
      { internalType: "uint8", name: "homeLastDigit", type: "uint8" },
      { internalType: "uint8", name: "awayLastDigit", type: "uint8" },
      { internalType: "uint8", name: "qComplete", type: "uint8" },
      { internalType: "uint8", name: "quarter", type: "uint8" },
    ],
    name: "isWinner",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_contestStorage", type: "address" },
    ],
    name: "setContestStorage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_contestId", type: "uint256" },
      { internalType: "string", name: "_newTitle", type: "string" },
      { internalType: "string", name: "_newDescription", type: "string" },
    ],
    name: "updateContestInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
