export const abi = [
  {
    inputs: [{ internalType: "address", name: "router_", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "CooldownNotMet", type: "error" },
  { inputs: [], name: "EmptyArgs", type: "error" },
  { inputs: [], name: "EmptySource", type: "error" },
  { inputs: [], name: "GameNotCompleted", type: "error" },
  { inputs: [], name: "NoInlineSecrets", type: "error" },
  { inputs: [], name: "OnlyRouterCanFulfill", type: "error" },
  { inputs: [], name: "ScoreChangeIndexOutOfBounds", type: "error" },
  { inputs: [], name: "ScoreChangesAlreadyStored", type: "error" },
  { inputs: [], name: "WeekGamesAlreadyFinalized", type: "error" },
  { inputs: [], name: "WeekResultsAlreadyFinalized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      { indexed: false, internalType: "bytes", name: "error", type: "bytes" },
    ],
    name: "GameScoreError",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "GameScoresRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "GameScoresUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
    ],
    name: "OwnershipTransferRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "id", type: "bytes32" },
    ],
    name: "RequestFulfilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "id", type: "bytes32" },
    ],
    name: "RequestSent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "ScoreChangesRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "ScoreChangesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "weekId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "WeekGamesRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "weekId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "gameCount",
        type: "uint8",
      },
    ],
    name: "WeekGamesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "weekId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "WeekResultsRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "weekId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "gameCount",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "allGamesCompleted",
        type: "bool",
      },
    ],
    name: "WeekResultsUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "QUARTER_SCORES_REQUEST_COOLDOWN",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SCORE_CHANGES_REQUEST_COOLDOWN",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SCORE_CHANGES_SOURCE",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SOURCE",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WEEK_GAMES_SOURCE",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WEEK_RESULTS_SOURCE",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "areScoreChangesAvailable",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
    ],
    name: "calculateWeekId",
    outputs: [{ internalType: "uint256", name: "weekId", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "subscriptionId", type: "uint64" },
      { internalType: "uint32", name: "gasLimit", type: "uint32" },
      { internalType: "bytes32", name: "jobId", type: "bytes32" },
      { internalType: "uint256", name: "gameId", type: "uint256" },
    ],
    name: "fetchGameScores",
    outputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "subscriptionId", type: "uint64" },
      { internalType: "uint32", name: "gasLimit", type: "uint32" },
      { internalType: "bytes32", name: "jobId", type: "bytes32" },
      { internalType: "uint256", name: "gameId", type: "uint256" },
    ],
    name: "fetchScoreChanges",
    outputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "subscriptionId", type: "uint64" },
      { internalType: "uint32", name: "gasLimit", type: "uint32" },
      { internalType: "bytes32", name: "jobId", type: "bytes32" },
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
    ],
    name: "fetchWeekGames",
    outputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "subscriptionId", type: "uint64" },
      { internalType: "uint32", name: "gasLimit", type: "uint32" },
      { internalType: "bytes32", name: "jobId", type: "bytes32" },
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
    ],
    name: "fetchWeekResults",
    outputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "gameId", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "gameScoreChanges",
    outputs: [
      { internalType: "uint256", name: "packedScoreChanges", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "gameScoreErrors",
    outputs: [{ internalType: "bytes", name: "error", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "gameScoreRequests",
    outputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "gameScores",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "uint8", name: "qComplete", type: "uint8" },
      { internalType: "bool", name: "requestInProgress", type: "bool" },
      { internalType: "bool", name: "gameCompleted", type: "bool" },
      { internalType: "uint256", name: "packedQuarterScores", type: "uint256" },
      { internalType: "uint256", name: "packedQuarterDigits", type: "uint256" },
      { internalType: "uint8", name: "totalScoreChanges", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "getGameScores",
    outputs: [
      { internalType: "uint8", name: "homeQ1LastDigit", type: "uint8" },
      { internalType: "uint8", name: "homeQ2LastDigit", type: "uint8" },
      { internalType: "uint8", name: "homeQ3LastDigit", type: "uint8" },
      { internalType: "uint8", name: "homeFLastDigit", type: "uint8" },
      { internalType: "uint8", name: "awayQ1LastDigit", type: "uint8" },
      { internalType: "uint8", name: "awayQ2LastDigit", type: "uint8" },
      { internalType: "uint8", name: "awayQ3LastDigit", type: "uint8" },
      { internalType: "uint8", name: "awayFLastDigit", type: "uint8" },
      { internalType: "uint8", name: "qComplete", type: "uint8" },
      { internalType: "bool", name: "requestInProgress", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "getQuarterScores",
    outputs: [
      { internalType: "uint8", name: "homeQ1", type: "uint8" },
      { internalType: "uint8", name: "homeQ2", type: "uint8" },
      { internalType: "uint8", name: "homeQ3", type: "uint8" },
      { internalType: "uint8", name: "homeF", type: "uint8" },
      { internalType: "uint8", name: "awayQ1", type: "uint8" },
      { internalType: "uint8", name: "awayQ2", type: "uint8" },
      { internalType: "uint8", name: "awayQ3", type: "uint8" },
      { internalType: "uint8", name: "awayF", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "gameId", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    name: "getScoreChange",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "homeLastDigit", type: "uint8" },
          { internalType: "uint8", name: "awayLastDigit", type: "uint8" },
        ],
        internalType: "struct GameScoreOracle.ScoreChangeEvent",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "getScoreChanges",
    outputs: [
      {
        components: [
          { internalType: "uint8", name: "homeLastDigit", type: "uint8" },
          { internalType: "uint8", name: "awayLastDigit", type: "uint8" },
        ],
        internalType: "struct GameScoreOracle.ScoreChangeEvent[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "getTotalScoreChanges",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
    ],
    name: "getWeekGames",
    outputs: [
      { internalType: "uint256[]", name: "gameIds", type: "uint256[]" },
      { internalType: "uint256", name: "submissionDeadline", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
    ],
    name: "getWeekResults",
    outputs: [{ internalType: "uint8[]", name: "winners", type: "uint8[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "requestId", type: "bytes32" },
      { internalType: "bytes", name: "response", type: "bytes" },
      { internalType: "bytes", name: "err", type: "bytes" },
    ],
    name: "handleOracleFulfillment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "isGameCompleted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "quarterScoresLastRequestTime",
    outputs: [
      {
        internalType: "uint256",
        name: "lastUpdatedTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "requestTypes",
    outputs: [
      {
        internalType: "enum GameScoreOracle.RequestType",
        name: "requestType",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "scoreChangesLastRequestTime",
    outputs: [
      {
        internalType: "uint256",
        name: "lastUpdatedTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "timeUntilQuarterScoresCooldownExpires",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gameId", type: "uint256" }],
    name: "timeUntilScoreChangesCooldownExpires",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "to", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "weekId", type: "uint256" }],
    name: "weekGames",
    outputs: [
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "uint8", name: "gamesCount", type: "uint8" },
      { internalType: "bool", name: "isFinalized", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "requestId", type: "bytes32" }],
    name: "weekRequests",
    outputs: [{ internalType: "uint256", name: "weekId", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "weekId", type: "uint256" }],
    name: "weekResults",
    outputs: [
      { internalType: "uint256", name: "weekId", type: "uint256" },
      { internalType: "uint256", name: "packedResults", type: "uint256" },
      { internalType: "uint8", name: "gamesCount", type: "uint8" },
      { internalType: "bool", name: "isFinalized", type: "bool" },
      {
        internalType: "uint256",
        name: "tiebreakerTotalPoints",
        type: "uint256",
      },
      { internalType: "uint256", name: "tiebreakerGameId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
