export const abi = [
  {
    inputs: [
      { internalType: "address", name: "_treasury", type: "address" },
      { internalType: "address", name: "_gameScoreOracle", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "address", name: "target", type: "address" }],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "AddressInsufficientBalance",
    type: "error",
  },
  { inputs: [], name: "AlreadyClaimed", type: "error" },
  { inputs: [], name: "ContestDoesNotExist", type: "error" },
  { inputs: [], name: "ContestNotFinalized", type: "error" },
  { inputs: [], name: "FailedInnerCall", type: "error" },
  { inputs: [], name: "GamesNotFetched", type: "error" },
  { inputs: [], name: "InsufficientPayment", type: "error" },
  { inputs: [], name: "InvalidCurrency", type: "error" },
  { inputs: [], name: "InvalidEntryFee", type: "error" },
  { inputs: [], name: "InvalidGameScoreOracle", type: "error" },
  { inputs: [], name: "InvalidNFTContract", type: "error" },
  { inputs: [], name: "InvalidPayoutStructure", type: "error" },
  { inputs: [], name: "InvalidPredictions", type: "error" },
  { inputs: [], name: "InvalidSeasonType", type: "error" },
  { inputs: [], name: "InvalidTokenId", type: "error" },
  { inputs: [], name: "InvalidTreasury", type: "error" },
  { inputs: [], name: "InvalidWeekNumber", type: "error" },
  { inputs: [], name: "NoGamesProvided", type: "error" },
  { inputs: [], name: "NoPrizeToClaim", type: "error" },
  { inputs: [], name: "NoWinners", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "PayoutAlreadyComplete", type: "error" },
  { inputs: [], name: "PayoutPeriodNotStarted", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "ScoreAlreadyCalculated", type: "error" },
  { inputs: [], name: "ScoreNotCalculated", type: "error" },
  { inputs: [], name: "SubmissionDeadlinePassed", type: "error" },
  { inputs: [], name: "TooManyGames", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "WeekResultsNotFinalized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "seasonType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "weekNumber",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "year",
        type: "uint256",
      },
    ],
    name: "ContestCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "gameId",
        type: "uint256",
      },
      { indexed: false, internalType: "uint8", name: "winner", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalPoints",
        type: "uint256",
      },
    ],
    name: "GameResultUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
    ],
    name: "GamesFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      { indexed: false, internalType: "uint8", name: "score", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "position",
        type: "uint256",
      },
    ],
    name: "LeaderboardUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
    ],
    name: "OwnershipTransferRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "PayoutPeriodStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "predictor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "PredictionSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "winner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PrizeClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "contestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "correctPicks",
        type: "uint8",
      },
    ],
    name: "ScoreCalculated",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_GAMES_PER_WEEK",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PERCENT_DENOMINATOR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SCORE_CALCULATION_PERIOD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TREASURY_FEE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "calculateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "tokenIds", type: "uint256[]" },
    ],
    name: "calculateScoresBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "claimAllPrizes",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "contestId", type: "uint256" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "claimPrize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "contestLeaderboard",
    outputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "uint8", name: "score", type: "uint8" },
      { internalType: "uint256", name: "tiebreakerPoints", type: "uint256" },
      { internalType: "uint256", name: "submissionTime", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "contestTokenIds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "contests",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "address", name: "currency", type: "address" },
      { internalType: "uint256", name: "entryFee", type: "uint256" },
      { internalType: "uint256", name: "totalPrizePool", type: "uint256" },
      { internalType: "uint256", name: "totalEntries", type: "uint256" },
      { internalType: "uint256", name: "submissionDeadline", type: "uint256" },
      { internalType: "bool", name: "gamesFinalized", type: "bool" },
      { internalType: "bool", name: "payoutComplete", type: "bool" },
      { internalType: "uint256", name: "payoutDeadline", type: "uint256" },
      { internalType: "uint256", name: "tiebreakerGameId", type: "uint256" },
      {
        components: [
          { internalType: "uint8", name: "payoutType", type: "uint8" },
          {
            internalType: "uint256[]",
            name: "payoutPercentages",
            type: "uint256[]",
          },
        ],
        internalType: "struct Pickem.PayoutStructure",
        name: "payoutStructure",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "seasonType", type: "uint8" },
      { internalType: "uint8", name: "weekNumber", type: "uint8" },
      { internalType: "uint256", name: "year", type: "uint256" },
      { internalType: "address", name: "currency", type: "address" },
      { internalType: "uint256", name: "entryFee", type: "uint256" },
      { internalType: "uint8", name: "payoutType", type: "uint8" },
      { internalType: "uint256", name: "customDeadline", type: "uint256" },
    ],
    name: "createContest",
    outputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "gameResults",
    outputs: [
      { internalType: "uint256", name: "gameId", type: "uint256" },
      { internalType: "uint8", name: "winner", type: "uint8" },
      { internalType: "uint256", name: "totalPoints", type: "uint256" },
      { internalType: "bool", name: "isFinalized", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "gameScoreOracle",
    outputs: [
      { internalType: "contract GameScoreOracle", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContest",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "uint8", name: "seasonType", type: "uint8" },
          { internalType: "uint8", name: "weekNumber", type: "uint8" },
          { internalType: "uint256", name: "year", type: "uint256" },
          { internalType: "uint256[]", name: "gameIds", type: "uint256[]" },
          { internalType: "address", name: "currency", type: "address" },
          { internalType: "uint256", name: "entryFee", type: "uint256" },
          { internalType: "uint256", name: "totalPrizePool", type: "uint256" },
          { internalType: "uint256", name: "totalEntries", type: "uint256" },
          {
            internalType: "uint256",
            name: "submissionDeadline",
            type: "uint256",
          },
          { internalType: "bool", name: "gamesFinalized", type: "bool" },
          { internalType: "bool", name: "payoutComplete", type: "bool" },
          { internalType: "uint256", name: "payoutDeadline", type: "uint256" },
          {
            internalType: "uint256",
            name: "tiebreakerGameId",
            type: "uint256",
          },
          {
            components: [
              { internalType: "uint8", name: "payoutType", type: "uint8" },
              {
                internalType: "uint256[]",
                name: "payoutPercentages",
                type: "uint256[]",
              },
            ],
            internalType: "struct Pickem.PayoutStructure",
            name: "payoutStructure",
            type: "tuple",
          },
        ],
        internalType: "struct Pickem.PickemContest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContestGameIds",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContestLeaderboard",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "tokenId", type: "uint256" },
          { internalType: "uint8", name: "score", type: "uint8" },
          {
            internalType: "uint256",
            name: "tiebreakerPoints",
            type: "uint256",
          },
          { internalType: "uint256", name: "submissionTime", type: "uint256" },
        ],
        internalType: "struct Pickem.LeaderboardEntry[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContestTokenIds",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "getContestWinners",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserContests",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      { internalType: "uint256[]", name: "gameIds", type: "uint256[]" },
    ],
    name: "getUserPicks",
    outputs: [{ internalType: "uint8[]", name: "", type: "uint8[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getUserPrediction",
    outputs: [
      { internalType: "uint256", name: "contestId", type: "uint256" },
      { internalType: "address", name: "predictor", type: "address" },
      { internalType: "uint256", name: "submissionTime", type: "uint256" },
      { internalType: "uint256", name: "tiebreakerPoints", type: "uint256" },
      { internalType: "uint8", name: "correctPicks", type: "uint8" },
      { internalType: "bool", name: "scoreCalculated", type: "bool" },
      { internalType: "bool", name: "claimed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "contestId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "getUserTokensForContest",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextContestId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextTokenId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "onERC721Received",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pickemNFT",
    outputs: [
      { internalType: "contract IPickemNFT", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "predictions",
    outputs: [
      { internalType: "uint256", name: "contestId", type: "uint256" },
      { internalType: "address", name: "predictor", type: "address" },
      { internalType: "uint256", name: "submissionTime", type: "uint256" },
      { internalType: "uint256", name: "tiebreakerPoints", type: "uint256" },
      { internalType: "uint8", name: "correctPicks", type: "uint8" },
      { internalType: "bool", name: "scoreCalculated", type: "bool" },
      { internalType: "bool", name: "claimed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_oracle", type: "address" }],
    name: "setGameScoreOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_pickemNFT", type: "address" }],
    name: "setPickemNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_treasury", type: "address" }],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "contestId", type: "uint256" },
      { internalType: "uint8[]", name: "picks", type: "uint8[]" },
      { internalType: "uint256", name: "tiebreakerPoints", type: "uint256" },
    ],
    name: "submitPredictions",
    outputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "to", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "contestId", type: "uint256" }],
    name: "updateContestResults",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userContests",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userTokens",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
